export interface Theme {
  name: string;
  bg_color: string;
  title_color: string;
  text_color: string;
  icon_color: string;
  border_color: string;
  border_radius?: string;
}

export const themes: Record<string, Theme> = {
  default: {
    name: "Default",
    bg_color: "ffffff",
    title_color: "2f80ed",
    text_color: "434d58",
    icon_color: "4c71f2",
    border_color: "e4e2e2",
  },
  dark: {
    name: "Dark",
    bg_color: "0d1117",
    title_color: "58a6ff",
    text_color: "c9d1d9",
    icon_color: "58a6ff",
    border_color: "30363d",
  },
  radical: {
    name: "Radical",
    bg_color: "141321",
    title_color: "fe428e",
    text_color: "a9fef7",
    icon_color: "f8d847",
    border_color: "fe428e",
  },
  merko: {
    name: "Merko",
    bg_color: "0a0f0b",
    title_color: "abd200",
    text_color: "68b587",
    icon_color: "b7d364",
    border_color: "68b587",
  },
  gruvbox: {
    name: "Gruvbox",
    bg_color: "282828",
    title_color: "fabd2f",
    text_color: "ebdbb2",
    icon_color: "fe8019",
    border_color: "3c3836",
  },
  tokyonight: {
    name: "Tokyo Night",
    bg_color: "1a1b27",
    title_color: "7aa2f7",
    text_color: "c0caf5",
    icon_color: "bb9af7",
    border_color: "2f3549",
  },
  onedark: {
    name: "One Dark",
    bg_color: "282c34",
    title_color: "61afef",
    text_color: "abb2bf",
    icon_color: "e06c75",
    border_color: "3e4451",
  },
  cobalt: {
    name: "Cobalt",
    bg_color: "193549",
    title_color: "ffc600",
    text_color: "ffffff",
    icon_color: "ff628c",
    border_color: "1e466e",
  },
  synthwave: {
    name: "Synthwave",
    bg_color: "2b213a",
    title_color: "e2e9ec",
    text_color: "e5289e",
    icon_color: "ef8539",
    border_color: "e5289e",
  },
  dracula: {
    name: "Dracula",
    bg_color: "282a36",
    title_color: "ff6e96",
    text_color: "f8f8f2",
    icon_color: "bd93f9",
    border_color: "6272a4",
  },
  prussian: {
    name: "Prussian",
    bg_color: "172f45",
    title_color: "bddfff",
    text_color: "6e93b5",
    icon_color: "38a0ff",
    border_color: "2c5f7d",
  },
  monokai: {
    name: "Monokai",
    bg_color: "272822",
    title_color: "ae81ff",
    text_color: "f8f8f2",
    icon_color: "e6db74",
    border_color: "49483e",
  },
  vue: {
    name: "Vue",
    bg_color: "fffefe",
    title_color: "41b883",
    text_color: "2c3e50",
    icon_color: "41b883",
    border_color: "e4e2e2",
  },
  "shades-of-purple": {
    name: "Shades of Purple",
    bg_color: "2d2b55",
    title_color: "a599e9",
    text_color: "b362ff",
    icon_color: "fad000",
    border_color: "a599e9",
  },
  nightowl: {
    name: "Night Owl",
    bg_color: "011627",
    title_color: "c792ea",
    text_color: "d6deeb",
    icon_color: "ffeb95",
    border_color: "1e3a5f",
  },
  buefy: {
    name: "Buefy",
    bg_color: "ffffff",
    title_color: "7957d5",
    text_color: "363636",
    icon_color: "00d1b2",
    border_color: "e4e2e2",
  },
  "blue-green": {
    name: "Blue Green",
    bg_color: "0f1419",
    title_color: "5f819d",
    text_color: "3c4a52",
    icon_color: "79b8ff",
    border_color: "5f819d",
  },
  algolia: {
    name: "Algolia",
    bg_color: "050f2c",
    title_color: "00aeff",
    text_color: "ececec",
    icon_color: "00aeff",
    border_color: "1a2332",
  },
  "great-gatsby": {
    name: "Great Gatsby",
    bg_color: "000000",
    title_color: "ffa726",
    text_color: "ffd93d",
    icon_color: "ffb74d",
    border_color: "ffa726",
  },
  darcula: {
    name: "Darcula",
    bg_color: "242424",
    title_color: "ba5f17",
    text_color: "bebebe",
    icon_color: "cc7832",
    border_color: "3c3f41",
  },
  bear: {
    name: "Bear",
    bg_color: "1f2023",
    title_color: "e06c75",
    text_color: "d0d0d0",
    icon_color: "e06c75",
    border_color: "3c3f41",
  },
  "solarized-dark": {
    name: "Solarized Dark",
    bg_color: "002b36",
    title_color: "268bd2",
    text_color: "839496",
    icon_color: "b58900",
    border_color: "073642",
  },
  "solarized-light": {
    name: "Solarized Light",
    bg_color: "fdf6e3",
    title_color: "268bd2",
    text_color: "586e75",
    icon_color: "b58900",
    border_color: "eee8d5",
  },
  "chartreuse-dark": {
    name: "Chartreuse Dark",
    bg_color: "000000",
    title_color: "7fff00",
    text_color: "00ff00",
    icon_color: "7fff00",
    border_color: "1a1a1a",
  },
  nord: {
    name: "Nord",
    bg_color: "2e3440",
    title_color: "88c0d0",
    text_color: "d8dee9",
    icon_color: "81a1c1",
    border_color: "4c566a",
  },
  gotham: {
    name: "Gotham",
    bg_color: "0c1014",
    title_color: "2aa889",
    text_color: "599cab",
    icon_color: "99d1ce",
    border_color: "0c1014",
  },
  "material-palenight": {
    name: "Material Palenight",
    bg_color: "292d3e",
    title_color: "89ddff",
    text_color: "a6accd",
    icon_color: "82aaff",
    border_color: "434758",
  },
  "graywhite": {
    name: "Gray White",
    bg_color: "ffffff",
    title_color: "24292e",
    text_color: "24292e",
    icon_color: "24292e",
    border_color: "e1e4e8",
  },
  "vision-friendly-dark": {
    name: "Vision Friendly Dark",
    bg_color: "000000",
    title_color: "ffb000",
    text_color: "ffffff",
    icon_color: "785ef0",
    border_color: "ffffff",
  },
  "ayu-mirage": {
    name: "Ayu Mirage",
    bg_color: "1f2430",
    title_color: "5ccfe6",
    text_color: "cbccc6",
    icon_color: "ffd173",
    border_color: "2d3348",
  },
  "midnight-purple": {
    name: "Midnight Purple",
    bg_color: "000000",
    title_color: "9745f5",
    text_color: "ffffff",
    icon_color: "9f4bff",
    border_color: "1a1a2e",
  },
  calm: {
    name: "Calm",
    bg_color: "ffffff",
    title_color: "e07a5f",
    text_color: "3d405b",
    icon_color: "81b29a",
    border_color: "e4e2e2",
  },
  "flag-india": {
    name: "Flag India",
    bg_color: "ff9933",
    title_color: "000080",
    text_color: "138808",
    icon_color: "000080",
    border_color: "ffffff",
  },
  omni: {
    name: "Omni",
    bg_color: "191622",
    title_color: "ff79c6",
    text_color: "e1e1e6",
    icon_color: "bd93f9",
    border_color: "2d2a3e",
  },
  react: {
    name: "React",
    bg_color: "20232a",
    title_color: "61dafb",
    text_color: "ffffff",
    icon_color: "61dafb",
    border_color: "282c34",
  },
  jolly: {
    name: "Jolly",
    bg_color: "ffffff",
    title_color: "ff64da",
    text_color: "a960ff",
    icon_color: "ffb3b3",
    border_color: "e4e2e2",
  },
  maroongold: {
    name: "Maroon Gold",
    bg_color: "260000",
    title_color: "ffd700",
    text_color: "ffffff",
    icon_color: "ffd700",
    border_color: "3d0000",
  },
  yeblu: {
    name: "Yeblu",
    bg_color: "002046",
    title_color: "ffff00",
    text_color: "ffffff",
    icon_color: "ffff00",
    border_color: "003f8c",
  },
  "blueberry": {
    name: "Blueberry",
    bg_color: "1e2139",
    title_color: "5a67d8",
    text_color: "cbd5e0",
    icon_color: "4299e1",
    border_color: "2d3748",
  },
  slateorange: {
    name: "Slate Orange",
    bg_color: "36393f",
    title_color: "ff8c42",
    text_color: "dcddde",
    icon_color: "ff8c42",
    border_color: "4f545c",
  },
  kacho_ga: {
    name: "Kacho Ga",
    bg_color: "1a1a27",
    title_color: "bf94a4",
    text_color: "d9d9d9",
    icon_color: "bf94a4",
    border_color: "2d2d44",
  },
  outrun: {
    name: "Outrun",
    bg_color: "0a0a0f",
    title_color: "ff00ff",
    text_color: "00ffff",
    icon_color: "ff00ff",
    border_color: "1a1a2e",
  },
  ocean: {
    name: "Ocean",
    bg_color: "0e1e25",
    title_color: "4fc3f7",
    text_color: "ffffff",
    icon_color: "29b6f6",
    border_color: "1a2f3a",
  },
  peachpuff: {
    name: "Peach Puff",
    bg_color: "ffdab9",
    title_color: "8b4513",
    text_color: "654321",
    icon_color: "cd853f",
    border_color: "deb887",
  },
  transparent: {
    name: "Transparent",
    bg_color: "00000000",
    title_color: "58a6ff",
    text_color: "c9d1d9",
    icon_color: "58a6ff",
    border_color: "30363d",
  },
};

export function getTheme(themeName: string): Theme {
  return themes[themeName] || themes.default;
}

